
- name: Configure mysql 1
  copy:
    src: ../files/my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: Configure mysql 2
  template:
    src: ../templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

