- name: Check Mysql da cai dat chua
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Cai dat Mysql
  apt:
    name: "mysql-server"
    state: present
  when: not mysql_installed.stat.exists
  notify: restart mysql

- name: Cai dat pip module
  apt: 
    name: "python3-pip"
    state: present

# - name: Cai dat MySQL-python module
#   become: yes
#   pip:
#     name: pymysql
