- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Encrypt/Decrypt File
    vault: 
      path: "./main.yml"
      secret:  "123456"
      type: "encrypt"
      msg: ""
    register: result
  - debug: var=result

