- hosts: localhost
  become: yes
  tasks:
  - name: Encrypt/Decrypt File
    vault: 
      path: "/home/viet/Desktop/main.yml"
      secret:  "./password.txt"
      type: "decrypt"
      msg: "aaaaa"
    register: result
  - debug: var=result

